# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1li4mqTfSR7-xQ688x5VhQhwD1e-mrs_F
"""

import pandas as pd

df = pd.read_csv('exportt.csv')

df

df.columns

df_filtered = df[["tag","tavg","tmin","tmax"]]

df_filtered= df_filtered.dropna()

df_filtered

from sklearn import linear_model
from sklearn.model_selection import train_test_split

X=df_filtered[["tag"]].values
y=df_filtered[["tavg","tmin","tmax"]].values

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0,test_size=0.25)



from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

y_pred

print(model.intercept_)

print(model.coef_)

print(model.predict([[31]]))